name: proyecto

services:

  # ================================
  # SPRING CLOUDD
  # ================================

  mysql:
    image: mysql:8.0
    container_name: biblioteca-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: biblioteca_bd
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proyecto-final
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: biblioteca-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - proyecto-final
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./Config-server
    container_name: biblioteca-config-server
    ports:
      - "8888:8888"
    networks:
      - proyecto-final
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  eureka-server:
    build: ./eureka-server
    container_name: biblioteca-eureka-server
    ports:
      - "8761:8761"
    networks:
      - proyecto-final
    depends_on:
      config-server:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    container_name: biblioteca-api-gateway
    ports:
      - "8001:8001"
    networks:
      - proyecto-final
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://biblioteca-eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  # ================================
  # MICROSERVICIOS
  # ================================

  libros-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Libros/Dockerfile
    container_name: biblioteca-libros-service
    ports:
      - "1001:1001"
    networks:
      - proyecto-final
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://biblioteca-eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://biblioteca-config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://biblioteca-mysql:3306/biblioteca_bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_RABBITMQ_HOST: biblioteca-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  usuario-service:
    restart: on-failure
    build:
      context: .
      dockerfile: usuario-service/Dockerfile
    container_name: biblioteca-usuario-service
    ports:
      - "1003:1003"
    networks:
      - proyecto-final
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://biblioteca-eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://biblioteca-config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://biblioteca-mysql:3306/biblioteca_bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_RABBITMQ_HOST: biblioteca-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  prestamos-service:
    restart: on-failure
    build:
      context: .
      dockerfile: prestamos-service/Dockerfile
    container_name: biblioteca-prestamos-service
    ports:
      - "1002:1002"
    networks:
      - proyecto-final
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://biblioteca-eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://biblioteca-config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://biblioteca-mysql:3306/biblioteca_bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_RABBITMQ_HOST: biblioteca-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_LIBRO_SERVICE_BASE_URL: http://biblioteca-libros-service:1001
      APP_USUARIO_SERVICE_BASE_URL: http://biblioteca-usuario-service:1003

  trabajadores-service:
    restart: on-failure
    build:
      context: .
      dockerfile: trabajadores-service/Dockerfile
    container_name: biblioteca-trabajadores-service
    ports:
      - "1004:1004"
    networks:
      - proyecto-final
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://biblioteca-eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://biblioteca-config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://biblioteca-mysql:3306/biblioteca_bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_RABBITMQ_HOST: biblioteca-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest


  prometheus:
    image: prom/prometheus:latest
    container_name: biblioteca-prometheus
    ports:
      - "9090:9090"
    networks:
      - proyecto-final
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: biblioteca-grafana
    ports:
      - "3000:3000"
    networks:
      - proyecto-final
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  mysql_data:
  grafana-data:

networks:
  proyecto-final:
    external: true